### ISSUE TITLE
KeyError of _non_zero_coefficients_index_dict

### ISSUE THREAD

**Issue by nariaki3551** [recruit-tech/codable-model-optimizer#7]
KeyError occurs when I execute the following script.

- MacOS v12.5.1
- Python v3.9.13
- codable-model-optimizer v0.1.3

### script

```python
from codableopt import *

# set problem
problem = Problem()

# define variables
n = 10
x = [DoubleVariable(name=f"x{i}") for i in range(10)]

# define objective function
def obj_func(x):
    print(x)
    return sum(x[i] * x[i] for i in range(n))

# set objective function and its arguments
problem += Objective(obj_func, args_map={'x': x})

solver = OptSolver()

# generate optimization methods to be used within the solver
method = PenaltyAdjustmentMethod(steps=40000)

answer, is_feasible = solver.solve(problem, method)
print(f'answer:{answer}, answer_is_feasible:{is_feasible}')
```

### error

```
Traceback (most recent call last):
  File "/Users/hoge/cob_tmp.py", line 22, in <module>
    answer, is_feasible = solver.solve(problem, method)
  File "/usr/local/lib/python3.9/site-packages/codableopt/solver/opt_solver.py", line 88, in solve
    answer, is_feasible = opt_solver.solve(
  File "/usr/local/lib/python3.9/site-packages/codableopt/solver/optimizer/optimization_solver.py", line 85, in solve
    state = OptimizationSolver.__optimize(
  File "/usr/local/lib/python3.9/site-packages/codableopt/solver/optimizer/optimization_solver.py", line 151, in __optimize
    return optimizer.optimize(debug, debug_step_unit)
  File "/usr/local/lib/python3.9/site-packages/codableopt/solver/optimizer/optimizer.py", line 80, in optimize
    proposed_move_list = self._method.propose(self._state, step)
  File "/usr/local/lib/python3.9/site-packages/codableopt/solver/optimizer/method/penalty_adjustment_method.py", line 100, in propose
    self._proposal_list = variable.propose_low_penalty_move(state)
  File "/usr/local/lib/python3.9/site-packages/codableopt/solver/formulation/variable/solver_double_variable.py", line 58, in propose_low_penalty_move
    lower, upper = state.problem.constraints.liner_constraints.calc_var_range_in_feasible(
  File "/usr/local/lib/python3.9/site-packages/codableopt/solver/formulation/constraint/solver_liner_constraints.py", line 152, in calc_var_range_in_feasible
    non_zero_indexes = self._non_zero_coefficients_index_dict[var_index]
KeyError: 9
```

**Comment by tomomotofactory** [comment]
Thanks for letting me know about the bug. I fixed it in the merge.

**Comment by nariaki3551** [comment]
Thank you for fixing it!
